### ISSUE TITLE
关于绑定fragment的问题

### ISSUE THREAD

**Issue by liqingH** [dhhAndroid/RxLifecycle#1]
看代码绑定的是Activity的生命周期，那如果我fragment销毁了但activity没有销毁那fragment中的任务是不是不会被注销，还是说不需要注销？

**Comment by dhhAndroid** [comment]
@13631284918  这个问题我知道，目前这块在下个版本我会优化一下，目前比较忙，没时间维护。不过现在所以任务都会在activity销毁的时候都会注销掉。为了简化代码，fragment没有作详细的处理。下个版本一定改一下。Rxlifecycle-retrofit模块你可以看一下，这块用起来比较方便。基本可以解决所有网络请求导致的内存泄漏。

**Comment by dhhAndroid** [comment]
此项目停止维护，上述问题已经在新项目解决，请移步[RxLife](https://github.com/dhhAndroid/RxLife)查看新项目
